{% set name = "dagster_twilio" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.tar.gz
  sha256: 96a34882c28b370e82d598bad3906a874a1ef54b9bf9a2ea2c53f92ec7640de1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - dagster {{ version }}.*
    - twilio

test:
  imports:
    - dagster_twilio

about:
  home: https://github.com/dagster-io/dagster/tree/master/python_modules/libraries/dagster-twilio
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: A Dagster integration for twilio

extra:
  recipe-maintainers:
    - conda-forge/dagster
